# Most useful numpy functions to generate numpy array


Numpy is an important libraby for Data Science with Python since almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

This notebook will focus mainly on different ways of generating numpy arrays.
- creating numpy array of zeroes and ones
- creating identity matrix
- creating an array in range
- generating evenly spaced numbers between specified intervals
- reshaping numpy arrays.

In [1]:
#installing jovian
!pip install jovian --upgrade -q

In [2]:
#import jovian
import jovian

<IPython.core.display.Javascript object>

In [3]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ········
[jovian] Updating notebook "mayurjajoomj/numpy-array-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/mayurjajoomj/numpy-array-operations


'https://jovian.ai/mayurjajoomj/numpy-array-operations'

## 0. Creating a numpy array from Python list

In [25]:
#import numpy
import numpy as np

In [6]:
#create a python list
my_list = [1, 2, 3, 4]
print("List is: ", my_list)

#Create numpy array
array = np.array(my_list)
print("Numpy array is: ", array)

List is:  [1, 2, 3, 4]
Numpy array is:  [1 2 3 4]


This was one simple way of creating a numpy array, let's look at some in built functions to create numpy array

## 1. Numpy array of zeroes and ones
`np.zeros()` and `np.ones()`can be used to create array consisting of only zeroes or ones respectively.

In [9]:
#Zeroes
#Just pass the number of elements in the method to create numpy array of zeroes
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
#Ones
#similarly pass nummber of elements in np.ones to create numpy array of ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## 2. Creating Identity matrix
`np.eye()` is used to create an identity matrix

In [13]:
#Identity matrix
#Pass the shape of the identity matrix you wish to create
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

If you wish to create a square identity matrix (identity matrix with equal rows and columns)
Then, you may just pass one parameter to the function.
Example:

In [15]:
#Creating an identity matrix of shape 3x3
#One way is np.eye(3,3), easier way is:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "mayurjajoomj/numpy-array-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/mayurjajoomj/numpy-array-operations


'https://jovian.ai/mayurjajoomj/numpy-array-operations'

## 3. Creating numpy array in range : `np.arange()`

In [ ]:
This function is used to create an array of elements in the specified range.
The parameters passed are the range in which you want your element excluding the element in 2nd parameter.

Refer the below example.

In [20]:
#Create an array of elements from 1 t 10
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

The third parameter is the difference between each element.
Refer the example below:

In [22]:
#Create an array of odd numbers from 1 to 10
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [26]:
#Example 2
#Create an array of even numbers from 2 to 100
np.arange(2,101,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

## 4.  Evenly spaced numbers over a specified interval

`np.linspace`

To create an array of evenly spaced numbers, specify the interval range and the number of intervals.

Refer the example below.

In [30]:
#Example
#Creating 5 partitions between 1 to 5
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [48]:
#Example 2
#Creating 10 partitions between 1 and 100
np.linspace(1,100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [50]:
#Example 3
#Creating 5 partitions between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

If the third argument is not passed, the function by default returns 50 partitions between the specified range

In [51]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## 5. Reshape `np.reshape()`

Finally, let's learn how to reshape any array using `np.reshape()`

In [66]:
#Create a 1D array of 25 elements
arr = np.arange(0, 25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [59]:
#Check the shape of array
arr.shape

(25,)

In [67]:
#Change the shape of arr to (5, 5)
matrix = arr.reshape(5 ,5)

In [68]:
matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [71]:
matrix.shape

(5, 5)

Note: While reshaping an array, you must ensure that the array has enough elements to be reshaped to the desired shape.

Consider the below example:

In [73]:
#Example 2
matrix2 = arr.reshape(5, 6)

ValueError: cannot reshape array of size 25 into shape (5,6)

The above cell was not executed successfully as the desired shape (5, 6) needs atleast 5 * 6 = 30 elements.

In [76]:
#Example 3
matrix2 = arr.reshape(1, 25)
matrix2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [78]:
matrix2.shape

(1, 25)

Notice in the above example, the array shape was changed to (1,25) which earlier was (25, 1)

## Conclusion
Above were the most commonly used methods to generate numpy arrays.
Being a beginner to numpy, these were the functions which I used the most to generate numpy arrays and practice slicing and learn various other operations on numpy arrays.

You may also try learning `np.random` to generate random numbers.


In [80]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "mayurjajoomj/numpy-array-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/mayurjajoomj/numpy-array-operations


'https://jovian.ai/mayurjajoomj/numpy-array-operations'

In [81]:
jovian.submit(assignment="zero-to-pandas-a2")

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "mayurjajoomj/numpy-array-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/mayurjajoomj/numpy-array-operations
[jovian] Submitting assignment..
[jovian] Verify your submission at https://jovian.ai/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
